### ISSUE TITLE
None time_start and time_end

### ISSUE THREAD

**Issue by Sosnowsky** [sajidah-ahmed/cmod_functions#10]
In the guide how_to_use_raw_APD_datatset_function.ipynb, the function 
`ds = cmod.generate_raw_apd_dataset(shot_number=shot_number, time_start=None, time_end=None, subtract_background=True)`
is called, however, time_start and time_end cannot be None, as they are used later. Removing the arguments as in 
`ds = cmod.generate_raw_apd_dataset(shot_number=shot_number, subtract_background=True)`
and falling to the defaults (+- np.inf) solves the issue.

**Comment by sajidah-ahmed** [comment]
Sorry, I forgot to update the notebook after I made those changes to the function.
