### ISSUE TITLE
Add plotting JSAT to plot_ASP_MLP_profiles.ipynb 

### ISSUE THREAD

**Issue by gregordecristoforo** [sajidah-ahmed/cmod_functions#9]
Adam said the following about plotting profiles from ASP/MLP data:

> there was a step here as well that I would recommend of just plotting JSAT for all four pins and look for outliers associated with arcing

**Comment by sajidah-ahmed** [comment]
I've plotted JSAT from all four pins. For most of the probe pins, the second reciprocation has a sharp peak during the maximum plunge.

**Comment by gregordecristoforo** [comment]
Great! Thanks for adding this to the guide.
